### ISSUE TITLE
Icons added for Ko-Fi and Streamelements

### ISSUE THREAD

**Issue by DieBraaiMeester** [doras-to/doras#54]
Please add the icons for the following:

Ko-Fi - https://ko-fi.com/
StreamElements - https://streamelements.com/

**Comment by tommerty** [comment]
Hey @DieBraaiMeester, this one is sadly a no-go, at least in the icon pickers current form. The reason behind that would be due to the icon pack we use just currently don't have these icons. For reference, the icon pack we use is [Tabler icons](https://tabler-icons.io/).

If I could make suggestions, I would suggest using `rocket` for SE & `mug` for Ko-Fi. 

I know it's not a perfect solution, but an issue would be that if we change or add icon libraries, there would be inconsistencies with sizing, margins, etc.

We do plan on allowing users to upload custom icons in the future, so this should help solve this problem of missing icons, however rare as Tabler offers near 5k icons out of the box, even including the new Twitter one!

I'm gonna mark this as a "won't fix", as it'll cause a lot of inconsistencies, and users can add icons soon!
