### ISSUE TITLE
shapes dont take around links 

### ISSUE THREAD

**Issue by Noclasss** [doras-to/doras#66]
in image you can see selection but all have same outcome 

![Screenshot 2023-12-05 134901](https://github.com/doras-to/doras/assets/152980879/3a315350-c967-424c-a147-bea70175974e)
![Screenshot 2023-12-05 134916](https://github.com/doras-to/doras/assets/152980879/c492e369-5092-41da-b69a-ae960f85d430)

**Comment by tommerty** [comment]
Hey @Noclasss, it's because your image is a png with a transparent background! So it is there, but your image just isn't lining up because it's transparent! If you upload a different image without a transparent background you should be able to see the change 😄 

We may add something additional to this in the future such as setting a custom color for the background, etc. But the way it's currently implemented is working as expected 😃
